name: Build FRANCOR Frank Base Package
on:
  push:
    branches: [ master ]

jobs:
  build-package:
    runs-on: ubuntu-latest
    container: franc0r/ros2-francor-dev:galactic
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        path: francor_frank_base
      - name: Build
        run: |
          ls
          pwd
          colcon build