name: Build FRANCOR Frank Base Package
on:
  push:
    branches: [ master ]

jobs:
  build-package:
    runs-on: ubuntu-latest
    container: franc0r/ros2-francor-dev:galactic
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          /bin/bash -c "source /opt/ros/$ROS_DISTRO/setup.bash && colcon build"