name: Build FRANCOR Frank Base Package
on:
  push:
    branches: [ master ]

jobs:
  build-package:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /home/user/ros2_ws/src/
    container: franc0r/ros2-francor-dev:galactic
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: |
          ls
          pwd
          echo Test